version: '3.8'
services:
  app:
    container_name: vite
    image: node:latest
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
